name: cloudHub Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildAndDeploy:

    runs-on: ubuntu-latest

    steps:
    - name: checkout Code Repo
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build and deploy to CloudHub
      run: mvn clean deploy -DmuleDeploy --file pom.xml .maven/settings.xml

